# Generated by Django 4.2.24 on 2025-10-24 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
